language: go

go: 1.3

install: 
  - go get -u -v gopkg.in/yaml.v2
  - go get -u -v gopkg.in/check.v1
  - go get -u -v github.com/axw/gocov/gocov
  - go get -u -v github.com/mattn/goveralls
  - go get -u -v code.google.com/p/go.tools/cmd/cover

script:
  - $HOME/gopath/bin/goveralls -repotoken tBYPuxVYqhmzShJsdgh7FPTUYmarzaog5
